language: python

python:
- '3.7'

node_js:
- '11.8.0'

services:
- docker

install:
- ./install_dependencies.sh

script:
- coverage run --source="./matchmaker","./seqr","./reference_data" --omit="*/migrations/*","*/apps.py" manage.py test -p '*_tests.py' -v 2 reference_data seqr matchmaker
- coverage report --fail-under=99
- cd ui/
- npm test
- cd ..
- ./test_mcri_local_deployment.sh

addons:
  postgresql: '12.3'
