version: '2.4'

services:
  postgres:
    image: gcr.io/seqr-project/postgres:gcloud-prod
    container_name: mcri_postgres
    ports:
      - ${POSTGRES_SERVICE_PORT:-5433}:${POSTGRES_SERVICE_PORT:-5433}
    environment:
      - PGPORT=${POSTGRES_SERVICE_PORT:-5433}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-docker-compose-postgres-password}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -h postgres -U postgres
      interval: 5s
      timeout: 10s
      retries: 100


  redis:
    image: gcr.io/seqr-project/redis:gcloud-prod
    container_name: mcri_redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 100


  kibana:
    image: gcr.io/seqr-project/kibana:gcloud-prod
    container_name: mcri_kibana

    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_SERVICE_HOSTNAME=${ELASTICSEARCH_SERVICE_HOSTNAME:-host.docker.internal}
      - ELASTICSEARCH_SERVICE_PORT=${ELASTICSEARCH_SERVICE_PORT:-9200}
    healthcheck:
      test: bash -c "curl -s kibana:5601 | grep kibana"
      interval: 3s
      timeout: 5s
      retries: 100


  seqr:
    image: "${SEQR_CONTAINER_REGISTRY:-gcr.io/mcri-01}/${SEQR_IMAGE_NAME:-mcri-seqr}:${SEQR_IMAGE_TAG:-latest}"
    container_name: mcri_seqr
    ports:
      - ${SEQR_SERVICE_PORT:-80}:8000
    environment:
      - SEQR_GIT_BRANCH=${SEQR_GIT_BRANCH:?err}
      - SEQR_PRIVACY_VERSION=${SEQR_PRIVACY_VERSION:--1}
      - SEQR_TOS_VERSION=${SEQR_TOS_VERSION:--1}
      - PYTHONPATH=/seqr
      - BASE_URL=${BASE_URL:?err}
      - EMAIL_BACKEND=${EMAIL_BACKEND:-django.core.mail.backends.console.EmailBackend}
      - SMTP_EMAIL_HOST=${SMTP_EMAIL_HOST:-host.docker.internal}
      - SMTP_EMAIL_PORT=${SMTP_EMAIL_PORT:-25}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-seqr@seqr.mcri.edu.au}
      - STATIC_MEDIA_DIR=/seqr_static_files
      - POSTGRES_SERVICE_HOSTNAME=postgres
      - POSTGRES_SERVICE_PORT=${POSTGRES_SERVICE_PORT:-5433}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-docker-compose-postgres-password}
      - ELASTICSEARCH_SERVICE_HOSTNAME=${ELASTICSEARCH_SERVICE_HOSTNAME:-host.docker.internal}
      - ELASTICSEARCH_SERVICE_PORT=${ELASTICSEARCH_SERVICE_PORT:-9200}
      - REDIS_SERVICE_HOSTNAME=redis
      - KIBANA_SERVICE_HOSTNAME=kibana
      - PGHOST=postgres
      - PGPORT=${POSTGRES_SERVICE_PORT:-5433}
      - PGUSER=postgres
      - GUNICORN_WORKER_THREADS=4
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: bash -c "curl -s 'http://localhost:8000' | grep html"
