version: '3.4'

services:

  postgres:
    build:
      context: ../../mcri_deploy/docker/postgres

  redis:
    build:
      context: ../../mcri_deploy/docker/redis

  seqr:
    build:
      dockerfile: deploy/docker/seqr/Dockerfile
      context: ../../
