apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: default
  name: pd-standard-expandable-storage-class
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    name: pd-standard-expandable-storage-class
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
parameters:
  type: pd-standard
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
