apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-master-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-master-node

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-data-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-data

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-client-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-client-node

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-data-loading-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-data-loading-node
